### ISSUE TITLE
Request for robots.txt returns pwa application with 404 page

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/route717#1]
**Steps to reproduce**
1) content -> design -> configuration
2) edit global config
3) search engine robots -> create custom robots file and save
4) try to open `/robots.txt` page, it should return robots txt content from database, but instead it returns pwa 404 page.

If I disable route717 module robots.txt works as expected.

**Comment by eli-l** [comment]
Fixed in 1.1.1
